### ISSUE TITLE
trace information missing in map or flatMap operation after a webclient call

### ISSUE THREAD

**Issue by bijukunjummen** [Nike-Inc/wingtips#120]
Assume that I have a Spring `WebClient` available instrumented with `WingtipsSpringWebfluxExchangeFilterFunction`. Now if I were to use this `WebClient` to make a call, the http headers carry the appropriate trace headers. The issue however is that if subsequently, the response is chained with a `map` or `flatMap` then there is no root trace available there.

Here is a test case:

```
        Span rootSpan = Tracer.getInstance().startRequestWithRootSpan("root");
        var webClient = WebClient.builder()
                .baseUrl("http://localhost:" + localPort)
                .filter(new WingtipsSpringWebfluxExchangeFilterFunction())
                .build();


        final Mono<Map<String, String>> mapMono = webClient.get()
                .uri("/headers")
                .accept(MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON)
                .exchange()
                .flatMap(clientResponse ->
                        clientResponse.bodyToMono(new ParameterizedTypeReference<Map<String, String>>() {
                        }))
                .map(response -> {
                    LOGGER.info("In map operation");
                    Span currentSpan = Tracer.getInstance().getCurrentSpan();
                    assertThat(currentSpan).isNotNull();
                    assertThat(currentSpan.getTraceId()).isEqualTo(rootSpan.getTraceId());
                    return response;
                });
```

This test would fail. The underlying reason appears to be that the thread in the `map` operation, is the thread used by netty under the covers which has not been instrumented with any of the tracing information.

**Comment by nicmunroe** [comment]
Hey @bijukunjummen , sorry for the very late response on this.

It's become increasingly clear that we cannot rely on `WebClient` threading behaviors being consistent, especially between versions of Spring - even supposedly non-breaking version updates of Spring. You can see I just had to drop support for some of the minimal auto-magic tracing propagation wingtips was already attempting to do, due to a breaking change with how spring handles their threading: [see this comment in the javadocs](https://github.com/Nike-Inc/wingtips/blob/59d7f0ab5584306227fdb9066ac8940bb47a0254/wingtips-spring-webflux/src/main/java/com/nike/wingtips/spring/webflux/client/WingtipsSpringWebfluxExchangeFilterFunction.java#L70-L80).

☝️ _is important for your example as well, given that your example does not use `webClient.attribute(TracingState.class.getName(), TracingState.getCurrentThreadTracingState())` to propagate the tracing state. Please read the linked javadoc comment carefully, and start using the `webClient.attribute(...)` mechanism to do the initial tracing state propagation, otherwise you'll upgrade spring someday and all your WebClient calls will fail to do distributed tracing correctly!_

There may be some very complex way to auto-magic the tracing state onto threads as `WebClient` hops from thread to thread, but the effort required would undoubtedly be very large and I'd be skeptical about its fragility.

My recommendation on your specific question around `map` and `flatMap` would be to use the wingtips-java8 features (see [examples here](https://github.com/Nike-Inc/wingtips/tree/main/wingtips-java8)) to wrap your `map` and `flatMap` functions to ensure the proper tracing state is attached when those functions execute. Same idea as what we're dong [here](https://github.com/Nike-Inc/wingtips/blob/59d7f0ab5584306227fdb9066ac8940bb47a0254/samples/sample-spring-boot2-webflux/src/main/java/com/nike/wingtips/springboot2webfluxsample/controller/SampleController.java#L293-L298) in the SB2 webflux sample app.
